# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines bellow are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: ps-http-sim

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - arm64
      - amd64

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - use: buildx
    goarch: amd64
    image_templates:
      - ghcr.io/mattrobenolt/{{ .ProjectName }}:{{ .Tag }}-amd64
      - ghcr.io/mattrobenolt/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64
      - ghcr.io/mattrobenolt/{{ .ProjectName }}:v{{ .Major }}-amd64
      - ghcr.io/mattrobenolt/{{ .ProjectName }}:latest-amd64
    build_flag_templates:
      - --platform=linux/amd64
      - --target=release
  - use: buildx
    goarch: arm64
    image_templates:
      - ghcr.io/mattrobenolt/{{ .ProjectName }}:{{ .Tag }}-arm64
      - ghcr.io/mattrobenolt/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-arm64
      - ghcr.io/mattrobenolt/{{ .ProjectName }}:v{{ .Major }}-arm64
      - ghcr.io/mattrobenolt/{{ .ProjectName }}:latest-arm64
    build_flag_templates:
      - --platform=linux/arm64
      - --target=release

docker_manifests:
  - name_template: ghcr.io/mattrobenolt/{{ .ProjectName }}:{{ .Tag }}
    image_templates:
      - ghcr.io/mattrobenolt/{{ .ProjectName }}:{{ .Tag }}-amd64
      - ghcr.io/mattrobenolt/{{ .ProjectName }}:{{ .Tag }}-arm64
  - name_template: ghcr.io/mattrobenolt/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}
    image_templates:
      - ghcr.io/mattrobenolt/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64
      - ghcr.io/mattrobenolt/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-arm64
  - name_template: ghcr.io/mattrobenolt/{{ .ProjectName }}:v{{ .Major }}
    image_templates:
      - ghcr.io/mattrobenolt/{{ .ProjectName }}:v{{ .Major }}-amd64
      - ghcr.io/mattrobenolt/{{ .ProjectName }}:v{{ .Major }}-arm64
  - name_template: ghcr.io/mattrobenolt/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/mattrobenolt/{{ .ProjectName }}:latest-amd64
      - ghcr.io/mattrobenolt/{{ .ProjectName }}:latest-arm64


changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

announce:
  webhook:
    enabled: true
    endpoint_url: https://pkg.go.dev/fetch/github.com/mattrobenolt/{{ .ProjectName }}@{{ .Tag }}
